replicaCount: 1
image:
  repository: ghcr.io/defenseunicorns/uds-runtime
  # x-release-please-start-version
  tag: 0.3.0
  # x-release-please-end
  pullPolicy: IfNotPresent

package:
  gateway: admin
  host: runtime
  domain: "###ZARF_VAR_DOMAIN###"
