apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uds-runtime-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
