# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.test.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uds-runtime-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uds-runtime
            port:
              number: 8080
{{- end }}
