# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Service
metadata:
  name: uds-runtime
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: uds-runtime
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
