name: API Auth Tests
on:
  workflow_call:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Environment (Go, Node, Homebrew, UDS CLI, k3d)
        uses: ./.github/actions/setup

      - name: Run tests
        run: uds run test:api-auth
        timeout-minutes: 30

      - name: Debug Output
        uses: defenseunicorns/uds-common/.github/actions/debug-output@ea9db8ab9bfc4a5d87acd7d1af385aa8e44206d3 # v0.13.0

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@ea9db8ab9bfc4a5d87acd7d1af385aa8e44206d3 # v0.13.0
        with:
          suffix: api-auth
