# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # Runs at 9:00 AM UTC, which is 3:00 AM MT during Daylight Saving Time

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/pr-tests.yaml

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: "true"

      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment (Go, Node, Homebrew, UDS CLI, k3d)
        uses: ./.github/actions/setup

      - name: smoke-test
        run: uds run test:smoke

      - name: Publish
        run: |
          uds run build:publish-uds-runtime --set REF=nightly-unstable --set DIR=hack/nightly

      - name: Build binary artifacts
        run: |
          uds run build:all

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        working-directory: hack/nightly
        run: |
          # cleanup old release
          gh release delete nightly-unstable --cleanup-tag -y || true
          # generate new release
          gh release create nightly-unstable ./build/* ../../build/*\
            -t "nightly-unstable" \
            --prerelease \
            -n 'Nightly unstable build'
